version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=lazewallet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lazewallet
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: